
#Application Configuration
spring:
  application:
    name: catalogue-service

#Server Configuration
server:
  port: 8000

#Mongo Configuration
mongo:
  database : person-db
  url : mongodb+srv://my_user:WROLgDt2JRYBokMS@cluster0-rrnyw.mongodb.net/test?retryWrites=true&w=majority


